services:
  go_scraper:
    build:
      dockerfile: ./Dockerfile-dev
      context: .
      no_cache: true
    ports:
      - 5000:5000
    mem_limit: 2G
    # cpus: 1
    volumes:
      - ./:/usr/src/app/
      # Mount Go module cache to speed up builds
      # - go-mod-cache:/go/pkg/mod
